---
title: "Stat 425 Final Case Study"
author: "Charlie Marcou, Carrie Mecca, Jessie Bustin"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# Load libraries
library(tidyverse)

# Load Data
bubblewrap <- read.csv("bubblewrap.csv")

# Remove Runs 2,3, and 5 for Replication 2
# Rows 11, 12, 17 
bubblewrap <- bubblewrap[-c(11, 12, 17), ]

# Convert to factors
bubblewrap <- bubblewrap %>%
  mutate(loading = as.factor(loading)) %>%
  mutate(line_speed = as.factor(line_speed))
```

```{r}
# Checking Full Model vs Additive Model using partial F test since we have an unbalanced ANOVA
full.model = lm(rate~line_speed*loading, bubblewrap)
additive.model = lm(rate~line_speed+loading, bubblewrap)
anova(additive.model, full.model)

# Fail To reject the null so the interaction term is not statistically significant and we select the additive model
```
```{r}
# Checking Main Effects
line_speed.model = lm(rate~line_speed, bubblewrap)
loading.model = lm(rate~loading, bubblewrap)

anova(line_speed.model, additive.model)
anova(loading.model, additive.model)

# We reject the line_speed.model at alpha = 0.1
# We fail to reject the loading.model
# Choosing the Loading Model
```

```{r}
# Pairwise Comparisons
pairwise.t.test(bubblewrap$rate, bubblewrap$loading, p.adjust.method = "bonferroni")

#Loadings 2 and 4 are different
```
```{r}
# Little bit of EDA
bubblewrap %>% 
  mutate(loading = as.factor(loading)) %>%
  ggplot(aes(x = loading, y = rate)) +
  geom_boxplot() +
  ggtitle("Rate Distributions By Loading")

bubblewrap %>%
  group_by(loading) %>%
  summarize(mean_rate = mean(rate), variance = var(rate))


# single 95% CI for difference between loadings 2 and 4

# Need to test for equal variance between the groups but guessing not
# Using Fischer's F Test
bubblewrap2 <- bubblewrap %>%
  filter(loading == 2)

bubblewrap4 <- bubblewrap %>%
  filter(loading == 4)

var.test(bubblewrap2$rate, bubblewrap4$rate)

# Yep, unequal variance so using a Welch's t-interval
t.test(bubblewrap2$rate, bubblewrap4$rate, var.equal = FALSE)

# 95% CI for a difference in means between loading 2 and 4 [-127.58643, -23.80246]
# We chose loading 4 as the highest production rate and line_speed is not significant
```

```{r model assumptions}

## Checking model assumptions
par(mfrow=c(1,2))
qqnorm(loading.model$res)
plot(loading.model$fitted, loading.model$res, xlab="Fitted", ylab="Residuals")

## We can note that the plot to check constant variance on the right, has a funneling inwards as we progress along the x axis. Additionally, based on the Q-Q plot normality seems light it might be questionable.

##Double checking normality with the shapiro-wilks test, we can see that using an alpha of .05, we fail to reject the null that the normality assumption is satistfied.
shapiro.test(loading.model$residuals)


```
```{r}
## Let's check if Box-Cox helps us here.
library(MASS)


loading.transformation=boxcox(loading.model,lambda=seq(-2,2, length=400))
lambda <- loading.transformation$x[which.max(loading.transformation$y)]
lambda

## Box-Cox would likely suggest a higher number if it was not constrained between -2 and 2, but because in practice it is only reccomended to use the technique within this range, we will stick with a lambda of 2

bubblewrap.transformed <- bubblewrap %>% 
    mutate(rate = (rate^lambda - 1)/ lambda)

transformed.loading.model = lm(rate~loading, bubblewrap.transformed)

## Rechecking model assumptions
par(mfrow=c(1,2))
qqnorm(transformed.loading.model$res)
plot(transformed.loading.model$fitted, transformed.loading.model$res, xlab="Fitted", ylab="Residuals")

## The Box-Cox transformation seems to perform slightly better, but does not make a huge change. The assumption seems to be unstatisfied still
```
```{r}
## Let us check our assumptions on other possible models we examined earlier.


## The Full Model has a problem with constant variance funneling in as well
par(mfrow=c(1,2))
qqnorm(full.model$res)
plot(full.model$fitted, full.model$res, xlab="Fitted", ylab="Residuals")

## The additive model also has a constant variance problem
par(mfrow=c(1,2))
qqnorm(additive.model$res)
plot(additive.model$fitted, additive.model$res, xlab="Fitted", ylab="Residuals")

## The line speed model also has a constant variance problem
par(mfrow=c(1,2))
qqnorm(line_speed.model$res)
plot(line_speed.model$fitted, line_speed.model$res, xlab="Fitted", ylab="Residuals")
```

