---
title: "Stat 425 Case Study 2"
author: "Jessie, Carrie, Charlie"
date: "`r Sys.Date()`"
output: html_document
---

## Case Study 2

```{r}
# Load Libraries
library(tidyverse)
library(leaps)
library(pls)
library(MASS)
library(lars)

# Load Data
crime <- read_table("crime.txt")

# Check For NA's and INF's
complete_rows <- crime[complete.cases(crime), ]
nrow(crime) == nrow(complete_rows)

# Convert factor col
crime <- crime %>%
  mutate(So = as.factor(So))

# Check Correlation
cor(crime[,-2])

# 3 highly correlated (Po1, Po2, and Wealth) 
# 2 highly correlated (U1, U2)
# 2 highly correlated (Ed, Ineq)
# Keeping Po1, U2, and Ed because they are highest with target
crimeNoCor <- crime %>%
  dplyr::select(-Po2, -Wealth, -U1, -Ineq)

#make this example reproducible
set.seed(425)

# Train Test Split
sample <- sample(c(TRUE, FALSE), nrow(crime), replace=TRUE, prob=c(0.7, 0.3))
train <- crime[sample, ]
test <- crime[!sample, ]

trainNoCor <- crimeNoCor[sample, ]
testNoCor <- crimeNoCor[!sample, ]
```

```{r}
# Run leaps and bounds
subset_selection = regsubsets(Crime~., data = trainNoCor)

rs = summary(subset_selection)
rs$bic #Model 8
rs 

model <- lm(Crime~So+NW+Pop+LF+U2+Po1+Ed+Prob, data = trainNoCor)

summary(model)

# Define RMSE function
rmse <- function(x,y) sqrt(mean((x-y)^2))

# Train RMSE
rmse(predict(model, trainNoCor), trainNoCor$Crime)

# Test RMSE
rmse(predict(model, testNoCor), testNoCor$Crime)
```

```{r}
#make this example reproducible
set.seed(425)

train <- train %>%
  mutate(So = as.numeric(So))

test <- test %>%
  mutate(So = as.numeric(So))

pcrcv <- pcr(Crime~., data = train, scale = TRUE, validation = "LOO", ncomp = 15)

pcrCV <- RMSEP(pcrcv, estimate="CV")

plot(pcrCV)

which.min(pcrCV$val) #8 components chosen by lowest CV RMSE

# Training RMSE
rmse(predict(pcrcv, train, ncom = 8), train$Crime)

# Get test RMSE
rmse(predict(pcrcv, test, ncom = 8), test$Crime) 
```

```{r}
#make this example reproducible
set.seed(425)

train <- trainNoCor %>%
  mutate(So = as.numeric(So))

test <- testNoCor %>%
  mutate(So = as.numeric(So))

# Choosing LASSO because it performs model selection
train.y <- train$Crime
train.x <- as.matrix(train[,-12])

test.y <- test$Crime
test.x <- as.matrix(test[,-12])

lasso <- lars(train.x, train.y)

cv.ml <- cv.lars(train.x,train.y)

which.min(cv.ml$cv)

svm <- cv.ml$index[which.min(cv.ml$cv)]
svm
plot(lasso)

# Train MSE
predlasso <- predict(lasso, train.x, s = svm, mode = "fraction")
rmse(train$Crime, predlasso$fit)

# Test MSE
predlasso <- predict(lasso, test.x, s = svm, mode = "fraction")
rmse(test$Crime, predlasso$fit)

coef(lasso, s=svm, mode="fraction")

```
